version: '3'

services:
  web:
    build:
      dockerfile: Docker-elixir  
      context: .
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    ports:
      - 4000:4000
    links:
      - db
  
  db:
    build:
      dockerfile: Docker-pg3 
      context: 
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - /postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:  